# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c84b9304a7a6654455b36510f551738c395566067a5e98100f1ed54d8eab1de6269a9345e9437a1bf252b466d0601f796490a53a3081610edc03b7967b5ddf02

test:
  secret_key_base: 4d05925c217f5e952c992dcb0c294fbfa65b299f3faba3003e0cc711f8dabf404229a82077f730c61f731ab2dcdf699be9d0282ca83d443d2d35053a9fc7a3b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
